### ISSUE TITLE
Why .2e-3 is not a number?

### ISSUE THREAD

**Issue by dryabov** [nst/JSONTestSuite#57]
It's one of forms for `2e-4`, and JavaScript supports it. The same is true for `2.e+3`, `2.e-3`, and `2.e3`.

**Comment by nst** [comment]
According to [json.org](http://json.org/) and [RFC 7159](https://tools.ietf.org/html/rfc7159):
`.2e-3` is invalid
`2e-4` is valid
`2.e+3`is invalid
`2.e-3`is invalid

![number](https://cloud.githubusercontent.com/assets/51388/20039004/56e14dc4-a43d-11e6-917d-1dfc5d4a96b7.gif)

Why? because it is the choices that Crockford make when he defined JSON grammar.

**Comment by dryabov** [comment]
Heh, used it many times (not exponential form, but smth like `.5`) in JavaScript and didn't know it's invalid. Shame on me.
